name: Deploy node project
on: push
jobs:
    pre_deploy:
        runs-on: ubuntu-latest
        steps:
        - name: Get code
          uses: actions/checkout@v4
        - name: Setup node
          uses: actions/setup-node@v4
        - name: Install project
          run: npm ci
        - name: Lint project
          run: npm run lint
        - name: test
          run: npm test
        - name: build
          run: npm run build
    deploy:
        needs: pre_deploy
        runs-on: ubuntu-latest
        steps:
        - name: Get code
          uses: actions/checkout@v4
        - name: Install project
          run: npm ci
        - name: Deploy project
          run: echo "Deploying project...."

      